version: '3.4'

services:
  devcontainer:
    container_name: devcontainer
    image: ghcr.io/ludeeus/devcontainer/integration:stable
    command: sleep infinity
    volumes:
      - .:/workspaces/sensorinterface
    ports:
      - 9123:8123
    networks:
      sensorif-dev:
        aliases:
          - devenv
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: sensorif-dev-mqtt
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      sensorif-dev:
        aliases:
          - mqtt
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./tests/stubs/mosquitto:/mosquitto/config
networks:
  sensorif-dev:
    name: sensorif-dev
