#!/usr/bin/env bash

# Make the config dir
rm -rf /tmp/config
ln -sf "${PWD}/tests/stubs/hass/config" /tmp


# Symplink the custom_components dir
if [ -d "/tmp/config/custom_components" ]; then
  rm -rf /tmp/config/custom_components
fi
ln -sf "${PWD}/custom_components" /tmp/config/custom_components



# Start Home Assistant
if [ ! -z "$1" ]; then
  hass -c /tmp/config &> $1
else
  hass -c/tmp/config
fi